uint8 OFF=0
uint8 BOOTING=1
uint8 INITIALIZING=2
uint8 READY=3
uint8 MISSION=4
uint8 EMERGENCY=5
uint8 RECOVERY=6
uint8 SHUTDOWN=7

uint8 requested_state 

---

bool accepted
string reason 
uint8 current_state
