controller_manager:
  ros__parameters:
    update_rate: 50 #"Hz"

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rear_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

rear_wheel_velocity_controller:
  ros__parameters:
    joints:
      - rear_left_wheel_joint